services:
  # Spring Boot Application
  - type: web
    name: petcare-app
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: JAVA_OPTS
        value: "-Xmx512m"
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: petcare-db
          property: connectionString
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        sync: false
      - key: JWT_SIGNER_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FACEBOOK_CLIENT_ID
        sync: false
      - key: FACEBOOK_CLIENT_SECRET
        sync: false
      - key: CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: VNPAY_TMN_CODE
        sync: false
      - key: VNPAY_SECRET
        sync: false

databases:
  - name: petcare-db
    databaseName: petcaremanagement
    user: petcare_user
    plan: free
